version: '3.8'

volumes:
  dev:
    external: true

services:
  web_server:
    image: php:apache
    container_name: ws
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - .conf/apache2:/etc/apache2
      - dev:/var/www/html:consistent
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    volumes:
      - .conf/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    volumes:
      - .conf/phpmyadmin:/var/www/html
    ports:
      - 8443:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
